Repository 202306-NEA-DZ-FEW/StudentStore, pull requests merged in 2023-11, with the labels that each got.

#58 Footer
  public/images/logo-footer.svg
  src/components/Buttons/__test__/Button.test.js
  src/components/Footer/Footer.jsx
  src/components/Footer/_test_/Footer.test.js
  src/components/Footer/_test_/__snapshots__/Footer.test.js.snap
  src/components/Language/Language.jsx
  src/pages/aboutus/index.jsx
  src/pages/allproducts/index.jsx
  src/pages/donations/index.jsx
  src/pages/index.jsx
Labels: enhancement, good first issue, design, component

#54 Navbar Component
  package-lock.json
  package.json
  public/Logo.svg
  src/components/Logo/Logo.jsx
  src/components/Logo/__test__/Logo.test.js
  src/components/Logo/__test__/__snapshots__/Logo.test.js.snap
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/__test__/NavBar.test.js
  src/components/NavBar/__test__/__snapshots__/NavBar.test.js.snap
  src/layout/Layout.jsx
Labels: enhancement, good first issue, design, component

#64 Create splash page
  public/logo.png
  public/splash.png
  src/components/AnimatedCounter/AnimatedCounter.jsx
  src/components/AnimatedCounter/__test__/AnimatedCounter.test.js
  src/components/AnimatedCounter/__test__/__snapshots__/AnimatedCounter.test.js.snap
  src/pages/index.jsx
  src/pages/splashpage.jsx
  src/styles/globals.css
Labels: enhancement, component

#69 Sign In page
  public/images/signin-bg.jpg
  public/images/signup-bg.jpg
  public/locales/ar/sign.json
  public/locales/en/sign.json
  public/locales/fr/sign.json
  public/signup-bg.jpg
  src/components/FacebookButton/FacebookButton.jsx
  src/components/FacebookButton/__test__/__snapshots__/FacebookButton.test.js.snap
  src/components/GoogleButton/GoogleButton.jsx
  src/components/GoogleButton/__test__/__snapshots__/GoogleButton.test.js.snap
  src/components/TwitterButton/TwitterButton.jsx
  src/components/TwitterButton/__test__/__snapshots__/TwitterButton.test.js.snap
  src/context/AuthContext.jsx
  src/pages/_app.jsx
  src/pages/forgotpassword/index.jsx
  src/pages/signin/index.jsx
  src/pages/signup/index.jsx
Labels: enhancement, firebase, authentication, translation

#70 Create Donation Page
  package-lock.json
  package.json
  public/images/donation1.jpg
  public/images/donation2.jpg
  public/images/donation3.jpg
  src/components/DonationSlider/DonationSlider.jsx
  src/components/DonationSlider/__test__/DonationSlider.test.js
  src/components/DonationSlider/__test__/__snapshots__/DonationSlider.test.js.snap
  src/components/PricingCard/PricingCard.jsx
  src/components/PricingCard/__test__/PricingCard.test.js
  src/components/PricingCard/__test__/__snapshots__/PricingCard.test.js.snap
  src/pages/donations/index.jsx
  src/styles/globals.css
Labels: enhancement

#74 Create Hero Section
  public/images/Hero1.svg
  public/images/cart-desktop.svg
  public/images/cart-mobile.svg
  public/images/checkout-desktop.svg
  public/images/checkout-mobile.svg
  public/images/globe-desktop.svg
  public/images/globe-mobile.svg
  src/components/HeroSection/HeroSection.jsx
  src/components/HeroSection/__test__/HeroSection.test.js
  src/components/HeroSection/__test__/__snapshots__/HeroSection.test.js.snap
Labels: enhancement, design, component

#85 Create navbar and fix merging issue
  src/components/Language/Language.jsx
  src/components/Language/__test__/__snapshots__/Language.test.js.snap
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/__test__/__snapshots__/NavBar.test.js.snap
  src/components/ProfileDropdown/ProfileDropdown.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/__test__/__snapshots__/SearchBar.test.js.snap
  src/components/SideBarNB/SideBarNB.jsx
  src/components/SideBarNB/__test__/SideBarNB.test.js
  src/components/SideBarNB/__test__/__snapshots__/SideBarNB.test.js.snap
  src/components/UnderBar/UnderBar.jsx
  src/pages/index.jsx
  src/styles/globals.css
Labels: bug, enhancement

#88 Testimonials Component
  public/images/testimonial1.jpg
  public/images/testimonial2.jpg
  public/images/testimonial3.jpg
  public/images/testimonial4.jpg
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/__test__/NavBar.test.js
  src/components/TestimonialsSection/TestimonialsSection.jsx
  src/components/TestimonialsSection/__test__/TestimonialsSection.test.js
  src/components/TestimonialsSection/__test__/__snapshots__/TestimonialsSection.test.js.snap
Labels: enhancement, component

#89 Enhance Listing Page
  src/components/Uploading/Uploading.jsx
  src/components/Uploading/__test__/Uploading.test.js
  src/components/Uploading/__test__/__snapshots__/Uploading.test.js.snap
  src/layout/Layout.jsx
  src/pages/Listings/index.jsx
  src/pages/index.jsx
  src/styles/globals.css
Labels: enhancement

#107 Add Page Load Progress Bar
  package-lock.json
  package.json
  src/components/PageLoadProgressBar/PageLoadProgressBar.jsx
  src/components/PageLoadProgressBar/__test__/PageLoaderProgressBar.test.js
  src/components/PageLoadProgressBar/__test__/__snapshots__/PageLoaderProgressBar.test.js.snap
  src/layout/Layout.jsx
  src/pages/404.jsx
Labels: enhancement, design, component

#113 ProductsContainer component
  src/components/ProductCard/ProductCard.jsx
  src/components/ProductCard/__test__/__snapshots__/ProductCard.test.js.snap
  src/components/ProductsContainer/ProductsContainer.jsx
  src/components/ProductsContainer/__test__/ProductsContainer.test.js
  src/components/ProductsContainer/__test__/__snapshots__/ProductsContainer.test.js.snap
  src/components/ProductsList/ProductsList.jsx
  src/components/ProductsList/__test__/ProductsList.test.js
  src/components/ProductsList/__test__/__snapshots__/ProductsList.test.js.snap
  src/pages/products/index.jsx
Labels: enhancement, firebase

#108 create Events Card
  public/Event.jpg
  public/bookbuddies.jpg
  public/photography.jpg
  src/components/EventCard/EventCard.jsx
  src/components/EventCard/__test__/EventCard.test.js
  src/components/EventCard/__test__/__snapshots__/EventCard.test.js.snap
  src/pages/index.jsx
Labels: enhancement

#122 Add functionality to the Underbar
  src/components/Filter/Filter.jsx
  src/components/Filter/__test__/__snapshots__/Filter.test.js.snap
  src/components/Logo/Logo.jsx
  src/components/Logo/__test__/__snapshots__/Logo.test.js.snap
  src/components/ProductsContainer/__test__/__snapshots__/ProductsContainer.test.js.snap
  src/components/SideBarNB/SideBarNB.jsx
  src/components/UnderBar/UnderBar.jsx
  src/components/UnderBar/__test__/UnderBar.test.js
  src/components/UnderBar/__test__/__snapshots__/UnderBar.test.js.snap
  src/pages/products/index.jsx
  src/pages/signin/index.jsx
Labels: enhancement

#124 Home Page implementation
  src/components/Footer/Footer.jsx
  src/components/Footer/_test_/__snapshots__/Footer.test.js.snap
  src/components/HeroSection/HeroSection.jsx
  src/components/HeroSection/__test__/__snapshots__/HeroSection.test.js.snap
  src/components/NavBar/NavBar.jsx
  src/layout/Layout.jsx
  src/pages/home/index.jsx
  src/pages/index.jsx
  src/pages/splashpage.jsx
Labels: enhancement

#131 Create component for the latest products
  src/components/FacebookButton/FacebookButton.jsx
  src/components/GoogleButton/GoogleButton.jsx
  src/components/LatestProducts/LatestProducts.jsx
  src/components/LatestProducts/__test__/LatestProducts.test.js
  src/components/LatestProducts/__test__/__snapshots__/LatestProducts.test.js.snap
  src/components/TwitterButton/TwitterButton.jsx
  src/pages/forgotpassword/index.jsx
  src/pages/home/index.jsx
  src/pages/products/index.jsx
  src/pages/signin/index.jsx
  src/pages/signup/index.jsx
Labels: enhancement, firebase

#134 Implement Multilingual Translation Functionality
  public/locales/ar/common.json
  public/locales/ar/donations.json
  public/locales/ar/home.json
  public/locales/en/common.json
  public/locales/en/home.json
  public/locales/fr/common.json
  public/locales/fr/donations.json
  public/locales/fr/home.json
  src/components/EventCard/EventCard.jsx
  src/components/EventCard/__test__/EventCard.test.js
  src/components/EventCard/__test__/__snapshots__/EventCard.test.js.snap
  src/components/Filter/__test__/Filter.test.js
  src/components/Footer/Footer.jsx
  src/components/Footer/_test_/__snapshots__/Footer.test.js.snap
  src/components/LatestProducts/LatestProducts.jsx
  src/components/LatestProducts/__test__/LatestProducts.test.js
  src/components/NavBar/NavBar.jsx
  src/components/ProfileDropdown/ProfileDropdown.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/__test__/SearchBar.test.js
  src/components/SearchBar/__test__/__snapshots__/SearchBar.test.js.snap
  src/components/SideBar/SideBar.jsx
  src/components/SideBarNB/SideBarNB.jsx
  src/components/TestimonialsSection/TestimonialsSection.jsx
  src/components/TestimonialsSection/__test__/TestimonialsSection.test.js
  src/components/TestimonialsSection/__test__/__snapshots__/TestimonialsSection.test.js.snap
  src/components/UnderBar/UnderBar.jsx
  src/components/UnderBar/__test__/UnderBar.test.js
  src/components/UnderBar/__test__/__snapshots__/UnderBar.test.js.snap
  src/layout/Layout.jsx
  src/pages/home/index.jsx
Labels: enhancement, design, translation

#137 Products Page
  public/locales/ar/products.json
  public/locales/en/products.json
  public/locales/fr/products.json
  src/components/Filter/Filter.jsx
  src/components/Filter/__test__/__snapshots__/Filter.test.js.snap
  src/components/ProductsContainer/ProductsContainer.jsx
  src/components/ProductsContainer/__test__/__snapshots__/ProductsContainer.test.js.snap
  src/components/ProductsList/ProductsList.jsx
  src/components/ProductsList/__test__/ProductsList.test.js
  src/components/ProductsList/__test__/__snapshots__/ProductsList.test.js.snap
  src/pages/products/index.jsx
  src/pages/signup/index.jsx
Labels: enhancement, firebase

#148 Implement image deletion functionality in listing page
  public/locales/fr/listing.json
  src/components/ListingForm/ListingForm.jsx
  src/components/ListingForm/__test__/ListingForm.test.js
  src/components/ListingForm/__test__/__snapshots__/ListingForm.test.js.snap
  src/components/ListingImages/ListingImages.jsx
  src/components/ListingImages/__test__/ListingImages.test.js
  src/components/ListingImages/__test__/__snapshots__/ListingImages.test.js.snap
  src/components/ProductCard/ProductCard.jsx
  src/pages/listing/index.jsx
Labels: bug, enhancement, component

#151 Searchbar functionality and Loader component
  package-lock.json
  package.json
  public/locales/ar/common.json
  public/locales/en/common.json
  public/locales/fr/common.json
  src/components/EventCard/EventCard.jsx
  src/components/EventCard/__test__/__snapshots__/EventCard.test.js.snap
  src/components/HeroSection/HeroSection.jsx
  src/components/HeroSection/__test__/__snapshots__/HeroSection.test.js.snap
  src/components/Loader/Loader.jsx
  src/components/Loader/__test__/Loader.test.js
  src/components/Loader/__test__/__snapshots__/Loader.test.js.snap
  src/components/NavBar/NavBar.jsx
  src/components/ProductsContainer/__test__/__snapshots__/ProductsContainer.test.js.snap
  src/components/ProductsList/ProductsList.jsx
  src/components/ProductsList/__test__/__snapshots__/ProductsList.test.js.snap
  src/components/SearchBar/SearchBar.jsx
  src/components/SideBarNB/SideBarNB.jsx
  src/components/UnderBar/UnderBar.jsx
  src/components/UnderBar/__test__/__snapshots__/UnderBar.test.js.snap
  src/layout/Layout.jsx
  src/pages/products/index.jsx
Labels: enhancement

#155 Implement "Add" Button in the Navbar and Sidebar
  public/locales/ar/common.json
  public/locales/en/common.json
  public/locales/fr/common.json
  src/components/NavBar/NavBar.jsx
  src/components/SideBarNB/SideBarNB.jsx
  src/components/UnderBar/UnderBar.jsx
  src/components/UnderBar/__test__/__snapshots__/UnderBar.test.js.snap
Labels: enhancement, translation

#158 Enhance the footer
  public/locales/ar/common.json
  public/locales/en/common.json
  public/locales/fr/common.json
  src/components/Footer/Footer.jsx
  src/components/Footer/_test_/Footer.test.js
  src/components/Footer/_test_/__snapshots__/Footer.test.js.snap
  src/components/NavBar/NavBar.jsx
  src/components/ProductsContainer/ProductsContainer.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/__test__/__snapshots__/SearchBar.test.js.snap
  src/components/SideBarNB/SideBarNB.jsx
  src/components/UnderBar/UnderBar.jsx
  src/components/UnderBar/__test__/__snapshots__/UnderBar.test.js.snap
  src/pages/listing/index.jsx
Labels: enhancement, component

#159 Add animation to the pages
  package-lock.json
  package.json
  src/components/AnimatedCounter/AnimatedCounter.jsx
  src/components/TypingText/TypingText.jsx
  src/components/TypingText/__test__/TypingText.test.js
  src/components/TypingText/__test__/__snapshots__/TypingText.test.js.snap
  src/pages/index.jsx
Labels: enhancement, design

#161 Implement multilingual translation arabic and french for listings page
  public/locales/ar/myListings.json
  public/locales/en/myListings
  public/locales/fr/myListings.json
  src/components/SideBar/SideBar.jsx
  src/components/listingcard/ListingCard.jsx
  src/components/listingcard/__test__/__snapshots__/ListingCard.test.js.snap
  src/pages/mylistings/index.jsx
Labels: enhancement, translation

#165 Create About us Page
  public/images/aboutus.svg
  public/images/hocine.jpg
  public/images/mounia.png
  public/images/sami.png
  public/locales/ar/aboutus.json
  public/locales/en/aboutus.json
  public/locales/fr/aboutus.json
  src/components/Faq/__test__/Faq.jsx
  src/components/Faq/__test__/Faq.test.js
  src/components/Faq/__test__/__snapshots__/Faq.test.js.snap
  src/components/OurMission/OurMission.jsx
  src/components/OurMission/__test__/OurMission.test.js
  src/components/OurMission/__test__/__snapshots__/OurMission.test.js.snap
  src/components/OurTeam/OurTeam.jsx
  src/components/OurTeam/__test__/OurTeam.test.js
  src/components/OurTeam/__test__/__snapshots__/OurTeam.test.js.snap
  src/pages/aboutus/index.jsx
  src/styles/globals.css
Labels: enhancement, translation

#170 Faq Component
  public/locales/ar/aboutus.json
  public/locales/en/aboutus.json
  public/locales/fr/aboutus.json
  src/components/Faq/__test__/Faq.jsx
  src/components/Faq/__test__/Faq.test.js
  src/components/Faq/__test__/__snapshots__/Faq.test.js.snap
  src/components/OurMission/OurMission.jsx
  src/components/OurMission/__test__/__snapshots__/OurMission.test.js.snap
  src/components/OurTeam/OurTeam.jsx
  src/components/OurTeam/__test__/__snapshots__/OurTeam.test.js.snap
  src/pages/aboutus/index.jsx
  src/pages/home/index.jsx
Labels: component, translation

#171 Improve the hamburger menu styling
  public/locales/ar/aboutus.json
  public/locales/ar/common.json
  public/locales/en/common.json
  public/locales/en/myListings.json
  public/locales/fr/common.json
  src/components/EventCard/EventCard.jsx
  src/components/EventCard/__test__/__snapshots__/EventCard.test.js.snap
  src/components/NavBar/NavBar.jsx
  src/components/ProductCard/ProductCard.jsx
  src/components/ProfileDropdown/ProfileDropdown.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/__test__/__snapshots__/SearchBar.test.js.snap
  src/components/ShoppingCartIcon/ShoppingCartIcon.jsx
  src/components/ShoppingCartIcon/__test__/ShoppingCartIcon.test.js
  src/components/ShoppingCartIcon/__test__/__snapshots__/ShoppingCartIcon.test.js.snap
  src/components/SideBarNB/SideBarNB.jsx
  src/pages/cart/index.jsx
  src/pages/home/index.jsx
  src/pages/listing/index.jsx
Labels: bug, enhancement, design

#177 Enhance Homepage Components with Framer Motion Animations
  package-lock.json
  package.json
  src/components/EventCard/EventCard.jsx
  src/components/EventCard/__test__/__snapshots__/EventCard.test.js.snap
  src/components/LatestProducts/LatestProducts.jsx
  src/components/ProductsList/ProductsList.jsx
Labels: design

#183 Fix Profile picture changing bug in the SideBar component
  src/components/OurTeam/OurTeam.jsx
  src/components/OurTeam/__test__/__snapshots__/OurTeam.test.js.snap
  src/components/Profile/Profile.jsx
  src/components/ProfileDropdown/ProfileDropdown.jsx
  src/components/SideBar/SideBar.jsx
  src/pages/donations/index.jsx
  src/pages/index.jsx
  src/util/firebase.js
Labels: bug

#179 Update README.md
  README.md
  image-1.png
  image-10.png
  image-2.png
  image-3.png
  image-4.png
  image-5.png
  image-6.png
  image-7.png
  image-8.png
  image-9.png
  image.png
Labels: documentation

#185 Fix the Loader component displaying
  src/components/Footer/Footer.jsx
  src/components/Loader/Loader.jsx
  src/components/Loader/__test__/__snapshots__/Loader.test.js.snap
Labels: bug

#186 Fix event styling responsiveness
  public/images/khaoula.jpg
  public/images/tewfik.jpg
  public/locales/ar/home.json
  public/locales/en/home.json
  public/locales/fr/home.json
  src/components/EventCard/EventCard.jsx
  src/components/EventCard/__test__/EventCard.test.js
  src/components/EventCard/__test__/__snapshots__/EventCard.test.js.snap
  src/components/OurTeam/OurTeam.jsx
  src/components/OurTeam/__test__/__snapshots__/OurTeam.test.js.snap
Labels: bug, design
