Repository 202306-NEA-DZ-FEW/StudentStore, pull requests merged in 2023-10, with the labels that each got.

#3 Tailwind-CSS-And-DaisyUI-Setup
  package-lock.json
  package.json
  postcss.config.js
  src/styles/globals.css
  tailwind.config.js
Labels: enhancement, organization

#7 Firebase integration
  .github/workflows/issue-autolink.yml
  package-lock.json
  package.json
  src/pages/index.jsx
  src/util/firebase.js
Labels: enhancement

#9 Project-Structure
  src/components/Buttons/Buttons.jsx
  src/components/FeaturedUniversities/FeaturedUniversities.jsx
  src/components/Footer/Footer.jsx
  src/components/HeroSection/HeroSection.jsx
  src/components/Language/Language.jsx
  src/components/NavBar/NavBar.jsx
  src/components/ProductCard/ProductCard.jsx
  src/components/Profile/Profile.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/TestimonialsSection/TestimonialsSection.jsx
  src/components/UnderBar/UnderBar.jsx
Labels: documentation, organization

#25 Reusable button component
  package-lock.json
  package.json
  src/components/Buttons/Button.jsx
  src/components/Buttons/Buttons.jsx
  src/components/Buttons/__test__/Button.test.js
  src/components/Buttons/__test__/__snapshots__/Button.test.js.snap
Labels: enhancement, component

#26 Underbar component
  src/components/UnderBar/UnderBar.jsx
  src/components/UnderBar/__test__/UnderBar.test.js
  src/components/UnderBar/__test__/__snapshots__/UnderBar.test.js.snap
Labels: enhancement, component

#37 Add a search bar
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/__test__/SearchBar.test.js
  src/pages/index.jsx
  src/util/firebase.js
Labels: enhancement, design, component

#39 Language Translation dropdown
  next-i18next.config.js
  public/locales/ar/common.json
  public/locales/en/common.json
  public/locales/fr/common.json
  src/components/Language/Language.jsx
  src/components/Language/__test__/Language.test.js
  src/components/Language/__test__/__snapshots__/Language.test.js.snap
  src/components/SearchBar/__test__/__snapshots__/SearchBar.test.js.snap
  src/pages/index.jsx
Labels: enhancement, component

#49 SignUp page form structure
  src/components/GoogleButton/GoogleButton.jsx
  src/components/TwitterButton/TwitterButton.jsx
  src/pages/index.jsx
  src/pages/signup/index.jsx
Labels: enhancement, firebase

#53 Translate and Style Signup Page
  public/hands_box.png
  public/locales/ar/sign.json
  public/locales/en/sign.json
  public/locales/fr/sign.json
  public/signup-bg.jpg
  src/components/FacebookButton/FacebookButton.jsx
  src/components/FacebookButton/__test__/FacebookButton.test.js
  src/components/FacebookButton/__test__/__snapshots__/FacebookButton.test.js.snap
  src/components/GoogleButton/GoogleButton.jsx
  src/components/GoogleButton/__test__/GoogleButton.test.js
  src/components/GoogleButton/__test__/__snapshots__/GoogleButton.test.js.snap
  src/components/TwitterButton/TwitterButton.jsx
  src/components/TwitterButton/__test__/TwitterButton.test.js
  src/components/TwitterButton/__test__/__snapshots__/TwitterButton.test.js.snap
  src/pages/signup/index.jsx
Labels: enhancement, translation
